import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {GetServerSideProps} from 'next'

const inter = Inter({ subsets: ['latin'] })

type SongList = string[]

interface HomeProps {
  songList: SongList
}

export default function Home(props: HomeProps) {
  const {songList} = props
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          songList.map(song => <div key={song}>{song}</div>)
        }
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const resp: {
    data: SongList
  } = await (await fetch('http://localhost:3000/api/song')).json()


  // will be passed to the page component as props
  return {
    props: {
      songList: resp.data
    }, 
  }
  
}